version: '3.8'
services:
  pgtest:
    container_name: pgtest
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=datastore
    ports:
      - '5432:5432'
    volumes:
      - .dbdata:/var/lib/postgresql/datastore
volumes:
  db:
    driver: local